import Options
from os import unlink, symlink, popen
from os.path import exists
import os

srcdir = "."
blddir = "build"
VERSION = "0.0.1"

def set_options(opt):
  opt.tool_options("compiler_cxx")

def configure(conf):
  conf.check_tool("compiler_cxx")
  conf.check_tool("node_addon")

  tna_libdir=os.getcwd()

  # the suffix tn is used as the lib name 
  conf.env.append_value("LIBPATH_tn", tna_libdir)
  conf.env.append_value("LIB_tn", "TestNode")

def build(bld):
  obj = bld.new_task_gen("cxx", "shlib", "node_addon")
  obj.target = "helloworld"
  obj.source = "helloworld.cpp"
  obj.uselib = "tn"
  
  obj.cxxflags = ["-D_FILE_OFFSET_BITS=64", "-D_LARGEFILE_SOURCE"]

def shutdown():
  if Options.commands['clean']:
    if exists('helloworld.node'): unlink('helloworld.node')
  else:
    if exists('build/default/helloworld.node') and not exists('helloworld.node'):
      symlink('build/default/helloworld.node', 'helloworld.node')

